name: "Bootstrap"

exports: "bootstrap.js"

web: "[clientcide.com](http://clientcide.com)"

description: "Clientcide's plugins for MooTools and Twitter's Bootstrap CSS framework"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [Aaron Newton](http://clientcide.com)"

authors: "[Aaron Newton](http://clientcide.com)"

version: "1.0.6"

#mootools forge stuff:
author: anutron
category: Interface
tags: [interface, menu, tips, popup, layout, UI]
docs: http://dev.clientcide.com/?version=MooTools%20Bootstrap
demo: http://anutron.github.com/mootools-bootstrap/
current: 1.0.6

sources:
 - Source/Behaviors/Behavior.BS.Affix.js
 - Source/Behaviors/Behavior.BS.Dropdown.js
 - Source/Behaviors/Behavior.BS.FormValidator.js
 - Source/Behaviors/Behavior.BS.Popover.js
 - Source/Behaviors/Behavior.BS.Popup.js
 - Source/Behaviors/Behavior.BS.Popup.FormRequest.js
 - Source/Behaviors/Behavior.BS.Tabs.js
 - Source/Behaviors/Behavior.BS.Tooltip.js
 - Source/Behaviors/Delegator.BS.ShowPopup.js
 - Source/UI/Bootstrap.js
 - Source/UI/Bootstrap.Affix.js
 - Source/UI/Bootstrap.Dropdown.js
 - Source/UI/Bootstrap.Popover.js
 - Source/UI/Bootstrap.Popup.js
 - Source/UI/Bootstrap.Tooltip.js
 - Source/UI/CSSEvents.js
